name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.15'

      - name: Build Docs
        run: mdbook build

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.15'

      - name: Build Docs
        run: mdbook test && mdbook build 

      - name: Deploy to gh-pages  
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: book # The folder the action should deploy.